# https://transfersh.pleasemarkdarkly.com/J73Ny/docker-compose.yml%

version: "2.1"
networks:
  internal_network:
    ipam:
      config:
      - subnet: 172.255.0.0/16
        gateway: 172.255.0.1
services:      
  db:
#    restart: always
    container_name: ambar_db
    privileged: true
    networks:
      - internal_network
    image: land007/ambar-mongodb:latest
    environment:
      - cacheSizeGB=2
      - LANIP=172.255.0.10
    volumes:
      - ${PWD}/Container_Data/db:/data/db
    expose:
      - "27017"   
  es:
#    restart: always
    container_name: ambar_es
    privileged: true
    networks:
      - internal_network
    image: land007/ambar-es:latest
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - LANIP=172.255.0.10
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${PWD}/Container_Data/es:/usr/share/elasticsearch/data
  rabbit:
#    restart: always
    privileged: true
    container_name: ambar_rabbit
    networks:
      - internal_network
    image: land007/ambar-rabbit:latest
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    environment:
      - LANIP=172.255.0.10
    volumes:
      - ${PWD}/Container_Data/rabbit:/var/lib/rabbitmq
  redis:
#    restart: always
    privileged: true
    container_name: ambar_redis
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    image: land007/ambar-redis:latest
    expose:
      - "6379" 
    environment:
      - LANIP=172.255.0.10
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
#    restart: always
    privileged: true
    container_name: ambar_serviceapi
    networks:
      - internal_network
    image: land007/ambar-serviceapi:latest
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=ambar_en
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=
      - LANIP=172.255.0.10
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    container_name: ambar_webapi
#    restart: always
    privileged: true
    networks:
      - internal_network
    image: land007/ambar-webapi:latest
    expose:
      - "8080"
#    ports:
#      - "8080:8080"
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=  
      - LANIP=172.255.0.10
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    container_name: ambar_frontend
    image: land007/ambar-frontend:latest
#    restart: always
    privileged: true
    networks:
      - internal_network
    ports:
      - "3000:80"
    expose:
      - "80"
    environment:
      - api=
      - LANIP=172.255.0.10
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy
    container_name: ambar_pipeline
    image: land007/ambar-pipeline:latest
#    restart: always
    privileged: true
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
      - LANIP=172.255.0.10
  crawler2:
    depends_on: 
      serviceapi: 
        condition: service_healthy
    container_name: ambar_crawler 
    image: land007/ambar-local-crawler:latest
#    restart: always
    privileged: true
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=crawler2
      - LANIP=172.255.0.10
    volumes:
      -  $PWD/Container_Data/crawler_input:/usr/data
  node-http-proxy:
    depends_on: 
      frontend: 
        condition: service_healthy 
      webapi: 
        condition: service_healthy 
    image: land007/node-http-proxy:latest
    container_name: ambar_node-http-proxy
#    restart: always
    privileged: true
    networks:
      - internal_network
    expose:
      - "80"
      - "20022"
    ports:
      - "20080:80"
      - "20022:20022"
    environment:
      - http_proxy_paths=/api/ /
      - http_proxy_hosts=webapi frontend
      - http_proxy_ports=8080 80
      - ws_proxy_paths=/api/
      - ws_proxy_hosts=webapi
      - ws_proxy_ports=8080
      - LANIP=172.255.0.10
    volumes:
      -  ~/docker/node-http-proxy:/node
  portainer:
#    restart: always
    privileged: true
    container_name: ambar_portainer
    networks:
      - internal_network
    image: land007/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/Container_Data/portainer_data:/data
    expose:
      - "9000"
    ports:
      - "9001:9000"
    environment:
      - LANIP=172.255.0.10
  
